### ISSUE TITLE
Would you consider re-licensing this under LGPL?

### ISSUE THREAD

**Issue by kk49** [PredatorCZ/HavokLib#1]
Hi, 
I'm developing a tool (https://github.com/kk49/deca) under the MIT license and I would like to dynamically link against this library (and maybe ApexLib to avoid a duplicate effort). Would you be willing to change the license to LGPL? Or maybe I should just re-license to GPL.

**Comment by PredatorCZ** [comment]
Hello,
Licensing is always a sensitive topic.
The thing is, at the beginning, I wanted to release all library projects under Apache 2.0, however I couldn't use modules under GPL3 within them. For example ApexLib is using zstd (licensed under GPL) or XenoLib is using derivative work from GPL3 project. Unfortunetly, I had to adapt.
So instead, I used GPL on every one, for whenever I would need to add any GPL licensed project in a future.
I had also thought about dual licensing, but same rules apply here as for modular solution.
The only reason I use GPL is only for this kind of scenario (and also because I don't want them to be used in some closed source shenanigans. Yes they do exist.).
But no worries, GPL doesn't restrict you in any way (except for copyleft policy, which others must obey).
So even if I would change license on this library, there will be always ApexLib, that must be under GPL.

I hope that I explained at least a little bit.
